"""
LangGraph Checkpointing & Human-in-the-Loop: Email Approval Workflow (WP-2.7)

Demonstrates how LangGraph's checkpointer enables:
1. Automatic state persistence at breakpoints
2. Human approval gates before critical actions
3. State resumption and branching (approve/reject/modify)
4. Audit trails and observability

Workflow:
  generate_email → [INTERRUPT] → approval_check → send_email
                        ↓                         ↓
                   (User Reviews)            (Complete)
"""

import asyncio
import logging
import os
from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Dict, List, Optional
from typing_extensions import TypedDict

# LangChain & LangGraph imports
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.runnables import RunnableConfig

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger(__name__)


# ============================================================================
# STATE DEFINITIONS
# ============================================================================

class EmailApprovalState(TypedDict):
    """
    State for email approval workflow.
    
    Fields progress through:
    - recipient, subject: Input provided by user
    - body: Generated by LLM (generated_email node)
    - approval_status: Set by human reviewer (None → approved/rejected)
    - send_timestamp: Set when email sent
    - error_message: Set if any step fails
    """
    # Input fields
    recipient: str
    subject: str
    
    # Generated content
    body: Optional[str]
    generated_at: Optional[str]
    
    # Approval fields
    approval_status: Optional[str]  # "pending" | "approved" | "rejected"
    approval_notes: Optional[str]
    reviewed_at: Optional[str]
    
    # Output fields
    send_timestamp: Optional[str]
    error_message: Optional[str]
    
    # Metadata
    thread_id: Optional[str]
    step_history: List[Dict]


# ============================================================================
# ERROR DEFINITIONS
# ============================================================================

class EmailApprovalError(Exception):
    """Base exception for email approval workflow."""
    pass


class ValidationError(EmailApprovalError):
    """Raised when input validation fails."""
    pass


class ExecutionError(EmailApprovalError):
    """Raised when node execution fails."""
    pass


# ============================================================================
# VALIDATION FUNCTIONS
# ============================================================================

def validate_email(state: EmailApprovalState) -> Optional[str]:
    """
    Validate email address format.
    
    Returns error message if invalid, None if valid.
    """
    recipient = state.get("recipient", "")
    
    if not recipient:
        return "Recipient field is empty"
    
    if "@" not in recipient or "." not in recipient:
        return f"Invalid email format: {recipient}"
    
    if len(recipient) > 254:
        return "Email address too long"
    
    return None


def validate_subject(state: EmailApprovalState) -> Optional[str]:
    """Validate subject line."""
    subject = state.get("subject", "")
    
    if not subject:
        return "Subject field is empty"
    
    if len(subject) > 1000:
        return "Subject too long"
    
    return None


# ============================================================================
# NODE FUNCTIONS
# ============================================================================

async def generate_email(state: EmailApprovalState) -> EmailApprovalState:
    """
    Generate email body based on recipient and subject.
    
    This is the FIRST node in the workflow. After this completes,
    the workflow pauses at the interrupt_before=["send_email"] checkpoint.
    """
    logger.info(f"[generate_email] Starting for recipient: {state['recipient']}")
    
    try:
        # Validate input
        email_error = validate_email(state)
        if email_error:
            logger.error(f"[generate_email] Validation failed: {email_error}")
            state["error_message"] = email_error
            return state
        
        subject_error = validate_subject(state)
        if subject_error:
            logger.error(f"[generate_email] Validation failed: {subject_error}")
            state["error_message"] = subject_error
            return state
        
        # Simulate LLM call to generate email body
        logger.info(f"[generate_email] Generating body for subject: {state['subject']}")
        await asyncio.sleep(0.5)  # Simulate LLM latency
        
        # Generated email body (simulated)
        state["body"] = f"""Dear {state['recipient'].split('@')[0]},

{state['subject']}

Thank you for reaching out. We appreciate your inquiry and would like to provide you with the following information:

Key Points:
1. We understand your concern about the recent updates.
2. Our team has reviewed the feedback you provided.
3. We are committed to addressing all issues promptly.

Next Steps:
- A dedicated specialist will contact you within 24 hours
- We will provide detailed documentation of changes
- You will receive follow-up support as needed

Best regards,
Customer Service Team
AI Architecture Blueprints"""
        
        state["generated_at"] = datetime.now().isoformat()
        state["error_message"] = None
        state["step_history"] = state.get("step_history", [])
        state["step_history"].append({
            "step": "generate_email",
            "timestamp": state["generated_at"],
            "status": "success"
        })
        
        logger.info(f"[generate_email] Email body generated successfully")
        logger.info(f"[generate_email] Workflow PAUSED at interrupt checkpoint")
        
    except Exception as e:
        logger.error(f"[generate_email] Unexpected error: {e}")
        state["error_message"] = f"Generation failed: {str(e)}"
        state["step_history"].append({
            "step": "generate_email",
            "timestamp": datetime.now().isoformat(),
            "status": "error",
            "error": str(e)
        })
    
    return state


async def approval_check(state: EmailApprovalState) -> EmailApprovalState:
    """
    Route based on approval status.
    
    This node checks the approval status field (set by human during interrupt).
    Returns the next node to execute based on approval decision.
    """
    logger.info(f"[approval_check] Evaluating approval status: {state.get('approval_status')}")
    
    status = state.get("approval_status")
    
    if status == "approved":
        logger.info(f"[approval_check] Email APPROVED, proceeding to send")
        state["reviewed_at"] = datetime.now().isoformat()
    elif status == "rejected":
        logger.info(f"[approval_check] Email REJECTED")
        state["error_message"] = f"Email rejected by reviewer: {state.get('approval_notes', 'No reason provided')}"
        state["reviewed_at"] = datetime.now().isoformat()
    else:
        logger.warning(f"[approval_check] Invalid approval status: {status}")
        state["error_message"] = "Approval status must be 'approved' or 'rejected'"
    
    return state


def route_after_approval(state: EmailApprovalState) -> str:
    """
    Conditional routing after approval check.
    
    Returns the next node name based on approval status.
    """
    status = state.get("approval_status")
    
    if status == "approved":
        return "send_email"
    else:
        # Rejected or invalid status
        return END


async def send_email(state: EmailApprovalState) -> EmailApprovalState:
    """
    Send email to recipient.
    
    IMPORTANT: This node only executes if approval_status == "approved".
    This is enforced by the approval_check node and routing logic.
    """
    logger.info(f"[send_email] Attempting to send email to {state['recipient']}")
    
    try:
        # Double-check approval (defensive programming)
        if state.get("approval_status") != "approved":
            state["error_message"] = "Cannot send: email not approved"
            logger.error(f"[send_email] Email not approved, skipping send")
            return state
        
        # Validate email body exists
        if not state.get("body"):
            state["error_message"] = "Email body is empty"
            logger.error(f"[send_email] Email body is empty")
            return state
        
        # Simulate sending (with retry logic)
        max_retries = 3
        for attempt in range(1, max_retries + 1):
            try:
                logger.info(f"[send_email] Send attempt {attempt}/{max_retries}")
                await asyncio.sleep(0.3)  # Simulate email service latency
                
                # Simulate occasional failures
                if attempt < 2 and asyncio.random() > 0.7:
                    raise ExecutionError("Simulated email service error")
                
                # Success
                state["send_timestamp"] = datetime.now().isoformat()
                state["error_message"] = None
                state["step_history"].append({
                    "step": "send_email",
                    "timestamp": state["send_timestamp"],
                    "status": "success",
                    "attempt": attempt
                })
                
                logger.info(f"[send_email] Email sent successfully at {state['send_timestamp']}")
                return state
                
            except Exception as e:
                logger.warning(f"[send_email] Attempt {attempt} failed: {e}")
                
                if attempt < max_retries:
                    # Exponential backoff
                    wait_time = 0.5 * (2 ** (attempt - 1))
                    await asyncio.sleep(wait_time)
                else:
                    # All retries exhausted
                    state["error_message"] = f"Email send failed after {max_retries} attempts: {str(e)}"
                    state["step_history"].append({
                        "step": "send_email",
                        "timestamp": datetime.now().isoformat(),
                        "status": "error",
                        "error": state["error_message"]
                    })
                    logger.error(f"[send_email] {state['error_message']}")
                    return state
    
    except Exception as unexpected:
        logger.error(f"[send_email] Unexpected error: {unexpected}")
        state["error_message"] = f"Unexpected error: {str(unexpected)}"
        state["step_history"].append({
            "step": "send_email",
            "timestamp": datetime.now().isoformat(),
            "status": "error",
            "error": str(unexpected)
        })
    
    return state


async def log_completion(state: EmailApprovalState) -> EmailApprovalState:
    """Log workflow completion with final status."""
    final_status = "success" if state.get("send_timestamp") else "rejected"
    logger.info(f"[log_completion] Workflow completed with status: {final_status}")
    
    state["step_history"].append({
        "step": "log_completion",
        "timestamp": datetime.now().isoformat(),
        "status": final_status
    })
    
    return state


# ============================================================================
# GRAPH BUILDING
# ============================================================================

def build_email_approval_graph(
    checkpoint_path: str = None
) -> any:
    """
    Build the email approval workflow graph.
    
    Args:
        checkpoint_path: Deprecated parameter (kept for compatibility)
    
    Returns:
        Compiled graph with interrupts configured
    
    Note:
        In production, use:
        from langgraph.checkpoint.sqlite import SqliteSaver
        checkpointer = SqliteSaver(conn=sqlite3.connect("checkpoints.db"))
    """
    logger.info("Building email approval workflow graph...")
    
    # Create state graph
    graph = StateGraph(EmailApprovalState)
    
    # Add nodes
    logger.info("Adding nodes...")
    graph.add_node("generate_email", generate_email)
    graph.add_node("approval_check", approval_check)
    graph.add_node("send_email", send_email)
    graph.add_node("log_completion", log_completion)
    
    # Add edges
    logger.info("Adding edges...")
    graph.add_edge(START, "generate_email")
    graph.add_edge("generate_email", "approval_check")
    graph.add_conditional_edges(
        "approval_check",
        route_after_approval,
        {"send_email": "send_email", END: END}
    )
    graph.add_edge("send_email", "log_completion")
    graph.add_edge("log_completion", END)
    
    # Create checkpointer for state persistence
    logger.info("Creating in-memory checkpointer for demonstration")
    checkpointer = MemorySaver()
    
    # Compile graph with checkpointer and interrupts
    logger.info("Compiling graph with checkpointer and interrupts...")
    compiled_graph = graph.compile(
        checkpointer=checkpointer,
        interrupt_before=["send_email"]  # Pause BEFORE send_email node
    )
    
    logger.info("Graph compiled successfully")
    return compiled_graph


# ============================================================================
# WORKFLOW EXECUTION
# ============================================================================

async def run_approval_workflow_with_approval(
    recipient: str,
    subject: str,
    thread_id: Optional[str] = None,
    checkpoint_path: str = None
) -> Dict:
    """
    Execute email approval workflow and handle approval.
    
    Demonstrates:
    1. First execution: generate → pause at interrupt
    2. User approval via state update
    3. Second execution: resume from checkpoint → send → complete
    
    Args:
        recipient: Email address
        subject: Email subject line
        thread_id: Unique workflow execution ID
        checkpoint_path: Deprecated parameter (kept for compatibility)
    
    Returns:
        Final workflow state
    """
    if not thread_id:
        thread_id = f"email-{datetime.now().timestamp()}"
    
    logger.info("=" * 80)
    logger.info(f"WORKFLOW: Email Approval (thread_id={thread_id})")
    logger.info("=" * 80)
    
    # Build graph
    graph = build_email_approval_graph()
    
    # Configuration for checkpointer
    config = {"configurable": {"thread_id": thread_id}}
    
    # ========== STEP 1: Generate Email ==========
    logger.info("\n" + "=" * 80)
    logger.info("STEP 1: Generate Email")
    logger.info("=" * 80)
    
    initial_state = {
        "recipient": recipient,
        "subject": subject,
        "body": None,
        "generated_at": None,
        "approval_status": None,
        "approval_notes": None,
        "reviewed_at": None,
        "send_timestamp": None,
        "error_message": None,
        "thread_id": thread_id,
        "step_history": []
    }
    
    # First execution: generate → pause at interrupt
    logger.info(f"Invoking workflow with initial state...")
    result = graph.invoke(initial_state, config=config)
    
    logger.info(f"\nGenerated email body:\n{result['body']}")
    logger.info(f"\n⏸️  Workflow paused at 'send_email' interrupt")
    logger.info(f"Thread ID for resumption: {thread_id}")
    
    # ========== STEP 2: Simulate User Approval ==========
    logger.info("\n" + "=" * 80)
    logger.info("STEP 2: User Reviews and Approves")
    logger.info("=" * 80)
    
    logger.info("Simulating human review...")
    await asyncio.sleep(1)  # Simulate review time
    
    # Get current state from checkpoint
    logger.info("Retrieving state from checkpoint...")
    current_state = graph.get_state(config)
    
    # Update approval status
    logger.info("Updating approval status in state...")
    updated_values = current_state.values.copy()
    updated_values["approval_status"] = "approved"
    updated_values["approval_notes"] = "Looks good, ready to send"
    
    # Push updated state back to checkpoint
    graph.update_state(config, updated_values)
    logger.info("State updated in checkpoint")
    
    # ========== STEP 3: Resume and Send ==========
    logger.info("\n" + "=" * 80)
    logger.info("STEP 3: Resume from Checkpoint and Send")
    logger.info("=" * 80)
    
    # Resume from checkpoint (None input means "resume from last interrupt")
    logger.info("Resuming workflow from checkpoint...")
    final_result = graph.invoke(None, config=config)
    
    logger.info(f"\n✅ Email sent successfully!")
    logger.info(f"Sent at: {final_result['send_timestamp']}")
    logger.info(f"Status: {final_result.get('approval_status')}")
    
    # Log step history
    logger.info(f"\nStep History:")
    for i, step in enumerate(final_result.get("step_history", []), 1):
        logger.info(f"  {i}. {step['step']:20s} | {step['status']:10s} | {step['timestamp']}")
    
    logger.info("=" * 80)
    return final_result


async def run_approval_workflow_with_rejection(
    recipient: str,
    subject: str,
    thread_id: Optional[str] = None,
    checkpoint_path: str = None
) -> Dict:
    """
    Execute email approval workflow and reject.
    
    Demonstrates:
    1. First execution: generate → pause at interrupt
    2. User rejects via state update
    3. Second execution: resume from checkpoint → skip send → complete
    
    Args:
        recipient: Email address
        subject: Email subject line
        thread_id: Unique workflow execution ID
        checkpoint_path: Deprecated parameter (kept for compatibility)
    
    Returns:
        Final workflow state
    """
    if not thread_id:
        thread_id = f"email-reject-{datetime.now().timestamp()}"
    
    logger.info("=" * 80)
    logger.info(f"WORKFLOW: Email Approval with Rejection (thread_id={thread_id})")
    logger.info("=" * 80)
    
    # Build graph
    graph = build_email_approval_graph()
    
    config = {"configurable": {"thread_id": thread_id}}
    
    # ========== STEP 1: Generate Email ==========
    logger.info("\n" + "=" * 80)
    logger.info("STEP 1: Generate Email")
    logger.info("=" * 80)
    
    initial_state = {
        "recipient": recipient,
        "subject": subject,
        "body": None,
        "generated_at": None,
        "approval_status": None,
        "approval_notes": None,
        "reviewed_at": None,
        "send_timestamp": None,
        "error_message": None,
        "thread_id": thread_id,
        "step_history": []
    }
    
    result = graph.invoke(initial_state, config=config)
    logger.info(f"\nGenerated email body:\n{result['body']}")
    logger.info(f"\n⏸️  Workflow paused at 'send_email' interrupt")
    
    # ========== STEP 2: Simulate User Rejection ==========
    logger.info("\n" + "=" * 80)
    logger.info("STEP 2: User Reviews and Rejects")
    logger.info("=" * 80)
    
    logger.info("Simulating human review...")
    await asyncio.sleep(1)
    
    current_state = graph.get_state(config)
    updated_values = current_state.values.copy()
    updated_values["approval_status"] = "rejected"
    updated_values["approval_notes"] = "Body is too generic, needs more specific information"
    
    graph.update_state(config, updated_values)
    logger.info("Approval status set to REJECTED")
    
    # ========== STEP 3: Resume (skip send) ==========
    logger.info("\n" + "=" * 80)
    logger.info("STEP 3: Resume from Checkpoint")
    logger.info("=" * 80)
    
    final_result = graph.invoke(None, config=config)
    
    logger.info(f"\n❌ Email was rejected")
    logger.info(f"Reason: {final_result.get('approval_notes')}")
    logger.info(f"Error message: {final_result.get('error_message')}")
    logger.info(f"Send timestamp: {final_result.get('send_timestamp')} (None = not sent)")
    
    logger.info("=" * 80)
    return final_result


# ============================================================================
# MAIN
# ============================================================================

async def main():
    """
    Run the email approval workflow demonstration.
    
    Demonstrates:
    1. Approval workflow (generate → pause → approve → send)
    2. Rejection workflow (generate → pause → reject → skip send)
    """
    
    # Enable LangSmith tracing (optional)
    # Uncomment these lines to see traces in LangSmith dashboard
    # os.environ["LANGCHAIN_TRACING_V2"] = "true"
    # os.environ["LANGSMITH_API_KEY"] = "your-langsmith-api-key"
    
    print("\n" + "=" * 80)
    print("EMAIL APPROVAL WORKFLOW DEMONSTRATION")
    print("Work Product 2.7: Checkpointing & Human-in-the-Loop")
    print("=" * 80)
    
    # Demo 1: Approval workflow
    await run_approval_workflow_with_approval(
        recipient="alice@example.com",
        subject="Update on Your Recent Inquiry",
        thread_id="demo-approval-001",
        checkpoint_path="checkpoints_demo.db"
    )
    
    # Demo 2: Rejection workflow
    await run_approval_workflow_with_rejection(
        recipient="bob@example.com",
        subject="Account Status Update",
        thread_id="demo-rejection-001",
        checkpoint_path="checkpoints_demo.db"
    )
    
    print("\n" + "=" * 80)
    print("DEMONSTRATION COMPLETE")
    print("=" * 80)
    print("\nKey Takeaways:")
    print("1. ✓ State persisted at interrupt checkpoint")
    print("2. ✓ Workflow paused, awaiting human approval")
    print("3. ✓ Resumed from checkpoint with user's decision")
    print("4. ✓ Conditional routing based on approval status")
    print("5. ✓ Audit trail captured in step_history")
    print("\nTo see LangSmith traces, enable:")
    print("  export LANGCHAIN_TRACING_V2=true")
    print("  export LANGSMITH_API_KEY=your-key")


if __name__ == "__main__":
    asyncio.run(main())
